import { TreePine } from "lucide-react";
import ServicePageLayout, { ServiceActivity } from "@/components/ServicePageLayout";
import camelSafariImg from "@/assets/activities/camel-safari.jpg";
import camelSunsetImg from "@/assets/activities/camel-sunset.jpg";
import desertCampImg from "@/assets/activities/desert-camp.jpg";
import desertNightCampImg from "@/assets/activities/desert-night-camp.jpg";
import desertSunriseImg from "@/assets/activities/desert-sunrise.jpg";
import culturalDanceImg from "@/assets/activities/cultural-dance.jpg";
import specialEventsImg from "@/assets/activities/special-events.jpg";
import jeepSafariImg from "@/assets/activities/jeep-safari.jpg";
import sightseeingImg from "@/assets/activities/sightseeing.jpg";
import adventureImg from "@/assets/activities/adventure.jpg";

const activities: ServiceActivity[] = [
  {
    id: "sunrise-camel",
    title: "Half-Day Sunrise Camel Safari",
    description: "Enjoy a magical sunrise over the Thar dunes with breakfast served in the desert. Perfect for photography lovers.",
    price: 2350,
    priceLabel: "/person",
    duration: "5:00 AM – 11:00 AM",
    details: [
      "Ideal for travelers who want a quick desert experience",
      "Enjoy sunrise in the desert with golden light over dunes",
      "Breakfast served freshly cooked in the desert",
      "Great photography opportunities during sunrise",
      "Expert camel guide throughout the ride",
      "Start: ~5:00 AM | End: ~11:00 AM (same day)",
    ],
    image: desertSunriseImg,
  },
  {
    id: "sunset-camel",
    title: "Half-Day Sunset Camel Safari",
    description: "Camel ride through sand dunes with a stunning sunset and wood-fire dinner cooked by local guides.",
    price: 2450,
    priceLabel: "/person",
    duration: "1:30 PM – 9:30 PM",
    details: [
      "Perfect for people exploring the city during the day",
      "Camel ride through beautiful sand dunes",
      "Watch stunning sunset behind the dunes",
      "Dinner cooked on wood fire by local guides",
      "Start: ~1:30 PM | End: ~9:30 PM (same day)",
    ],
    image: camelSunsetImg,
  },
  {
    id: "one-day-camel",
    title: "One Day Camel Safari",
    description: "Full day desert experience with breakfast, lunch and dinner freshly cooked in the desert. Sunset on the dunes.",
    price: 2750,
    priceLabel: "/person",
    duration: "6:30 AM – 9:30 PM",
    minPeople: 2,
    details: [
      "Full day desert experience without overnight stay",
      "Morning camel ride with breakfast in the desert",
      "Rest under tree shade during afternoon",
      "Freshly cooked lunch and dinner in the desert",
      "Sunset views from the sand dunes",
      "Minimum 2 people required",
      "Start: ~6:30 AM | End: ~9:30 PM (same day)",
    ],
    image: camelSafariImg,
  },
  {
    id: "overnight-4a",
    title: "Overnight Camel Safari – 4A",
    description: "Non-touristic off-track desert route. Explore desert landscapes, huts, temples, flora & fauna. Sleep under the stars.",
    price: 3650,
    priceLabel: "/person",
    duration: "6:30 AM – 11:00 AM next day",
    details: [
      "Non-touristic off-track desert route away from crowds",
      "Explore desert landscapes, huts, and temples",
      "Observe local flora and fauna along the way",
      "Sleep under the stars with warm bedding provided",
      "All meals (breakfast, lunch, dinner) included",
      "Start: ~6:30 AM | End: ~11:00 AM next day",
    ],
    image: desertNightCampImg,
  },
  {
    id: "overnight-4b",
    title: "Overnight Camel Safari – 4B",
    description: "Experience nomadic desert life. Ride across scrublands, fields, rocky areas and dunes. Spot local wildlife.",
    price: 4150,
    priceLabel: "/person",
    duration: "6:30 AM – 5:30 PM next day",
    details: [
      "Experience authentic nomadic desert life",
      "Camel ride across scrublands, fields, rocky areas and dunes",
      "Spot local wildlife including desert foxes and birds",
      "Sleep under the stars with warm bedding",
      "All meals freshly cooked in the desert",
      "Start: ~6:30 AM | End: ~5:30 PM next day",
    ],
    image: sightseeingImg,
  },
  {
    id: "overnight-4c",
    title: "Overnight Camel Safari – 4C",
    description: "Raw desert experience on non-touristic routes through farms, rocky areas and dunes. Sleep under the stars.",
    price: 2950,
    priceLabel: "/person",
    duration: "1:30 PM – 11:00 AM next day",
    details: [
      "Raw desert experience on non-touristic routes",
      "Camel ride through farms, rocky areas and sand dunes",
      "Observe local flora and fauna",
      "Sleep under the stars with warm bedding",
      "Dinner and breakfast included",
      "Start: ~1:30 PM | End: ~11:00 AM next day",
    ],
    image: adventureImg,
  },
  {
    id: "overnight-4d",
    title: "Overnight Camel Safari – 4D",
    description: "Off-beat desert safari through dunes and scrublands. Pass mud houses and temples. Overnight under stars.",
    price: 3650,
    priceLabel: "/person",
    duration: "1:30 PM – 5:30 PM next day",
    details: [
      "Off-beat desert safari experience",
      "Ride through dunes and scrublands",
      "Pass traditional mud houses and ancient temples",
      "Overnight stay under the stars with warm bedding",
      "All meals included",
      "Start: ~1:30 PM | End: ~5:30 PM next day",
    ],
    image: jeepSafariImg,
  },
  {
    id: "camping",
    title: "Camping in the Desert",
    description: "Camel ride across farms, dunes and rocky landscapes. Camp in a desert tent with warm bedding among sand dunes.",
    price: 3450,
    priceLabel: "/person",
    duration: "1:30 PM – 11:00 AM next day",
    details: [
      "Camel ride across farms, dunes and rocky landscapes",
      "Camp in a desert tent set among sand dunes",
      "Warm bedding provided inside the tent",
      "Dinner and breakfast freshly cooked",
      "Start: ~1:30 PM | End: ~11:00 AM next day",
    ],
    image: desertCampImg,
  },
  {
    id: "real-desert",
    title: "Real Desert Safari",
    description: "2 nights / 3 days experience. First night under the stars, second in luxury camp. Cultural dance & music.",
    price: 7950,
    priceLabel: "/person",
    duration: "2 Nights / 3 Days",
    details: [
      "2 nights / 3 days immersive desert experience",
      "First night sleeping under the stars",
      "Second night in a luxury desert camp",
      "Camel ride with sunset and sunrise views",
      "Cultural dance and music program included",
      "All meals included throughout",
      "Start: ~1:30 PM | End: ~11:00 AM (third day)",
    ],
    image: specialEventsImg,
  },
  {
    id: "live-entertainment",
    title: "Camel Safari with Live Entertainment",
    description: "Camel ride to dunes with sunset, Rajasthani folk dance and music, and interaction with local gypsy community.",
    price: 3650,
    priceLabel: "/person",
    duration: "1:30 PM – 9:30 PM",
    details: [
      "Camel ride to the sand dunes",
      "Watch stunning sunset from the dunes",
      "Live Rajasthani folk dance and music performance",
      "Interaction with local gypsy community",
      "Dinner included",
      "Start: ~1:30 PM | End: ~9:30 PM (same day)",
    ],
    image: culturalDanceImg,
  },
  {
    id: "dance-music-overnight",
    title: "Camel Safari with Dance & Music",
    description: "Camel ride with sunset view, live Rajasthani dance & music performance, and overnight stay under star-lit sky.",
    price: 4450,
    priceLabel: "/person",
    duration: "1:30 PM – 11:00 AM next day",
    details: [
      "Camel ride through the desert with sunset view",
      "Live Rajasthani dance and music performance",
      "Overnight stay under the star-lit sky",
      "Warm bedding provided",
      "Dinner and breakfast included",
      "Start: ~1:30 PM | End: ~11:00 AM next day",
    ],
    image: camelSunsetImg,
  },
  {
    id: "cultural-program",
    title: "Camel Safari with Cultural Program",
    description: "Camel ride in dunes with traditional Rajasthani folk dance & music, welcome ceremony and dinner.",
    price: 3450,
    priceLabel: "/person",
    duration: "3:00 PM – 10:30 PM",
    details: [
      "Camel ride through the sand dunes",
      "Traditional Rajasthani folk dance and music show",
      "Traditional welcome ceremony on arrival",
      "Dinner served at desert camp seating arrangement",
      "Start: ~3:00 PM | End: ~10:30 PM (same day)",
    ],
    image: culturalDanceImg,
  },
  {
    id: "non-touristic",
    title: "Non-Touristic Desert Safari",
    description: "2 Nights / 3 Days through scrublands, farms and dunes. Camp under starry sky with traditional open-fire meals.",
    price: 2450,
    priceLabel: "/person/night",
    nights: 2,
    duration: "2 Nights / 3 Days",
    details: [
      "Camel ride through scrublands, farms and sand dunes",
      "Off-track non-touristic route away from crowds",
      "Camp under the starry sky each night",
      "Traditional meals cooked on open fire",
      "Warm bedding provided",
      "Start: ~6:30 AM or ~1:30 PM | End: ~11:00 AM or ~5:30 PM (3rd day)",
    ],
    image: desertNightCampImg,
  },
  {
    id: "into-thar",
    title: "Into The Thar Desert Safari",
    description: "3 Nights / 4 Days deep desert exploration. Camel rides across dunes and rocky landscapes with traditional meals.",
    price: 2350,
    priceLabel: "/person/night",
    nights: 3,
    duration: "3 Nights / 4 Days",
    details: [
      "Deep desert exploration over 3 nights and 4 days",
      "Camel rides across sand dunes and rocky landscapes",
      "Camp under the stars each night",
      "Traditional meals cooked fresh in the desert",
      "Experience remote desert wilderness",
    ],
    image: desertSunriseImg,
  },
  {
    id: "thar-desert",
    title: "Thar Desert Safari",
    description: "4 Nights / 5 Days long camel expedition. Camp each night under the stars with sunset and sunrise views.",
    price: 2250,
    priceLabel: "/person/night",
    nights: 4,
    duration: "4 Nights / 5 Days",
    details: [
      "Long camel expedition spanning 4 nights and 5 days",
      "Camp each night under the stars",
      "Enjoy both sunset and sunrise views from dunes",
      "All meals freshly cooked in the desert",
      "Warm bedding provided each night",
    ],
    image: camelSafariImg,
  },
  {
    id: "nomad-experience",
    title: "The Nomad Experience",
    description: "5 Nights / 6 Days immersive desert experience. Camel rides across dunes and rocky terrain with traditional meals.",
    price: 2150,
    priceLabel: "/person/night",
    nights: 5,
    duration: "5 Nights / 6 Days",
    details: [
      "Immersive 5-night desert experience",
      "Camel rides across dunes and rocky terrain",
      "Traditional meals and desert camping each night",
      "Experience the true nomadic lifestyle",
      "Warm bedding and all supplies provided",
    ],
    image: desertCampImg,
  },
  {
    id: "exploring-thar",
    title: "Exploring the Thar",
    description: "6 Nights / 7 Days deep exploration of Thar landscapes. Camping under starry sky with open-fire meals.",
    price: 2050,
    priceLabel: "/person/night",
    nights: 6,
    duration: "6 Nights / 7 Days",
    details: [
      "Deep exploration of Thar Desert over 6 nights",
      "Camping under the starry sky each night",
      "Traditional open-fire meals throughout",
      "Visit remote desert areas and landscapes",
      "All supplies and bedding provided",
    ],
    image: sightseeingImg,
  },
  {
    id: "thar-compass",
    title: "Thar by the Compass",
    description: "7 Nights / 8 Days extensive desert journey across multiple terrains. Camp under the stars each night.",
    price: 1950,
    priceLabel: "/person/night",
    nights: 7,
    duration: "7 Nights / 8 Days",
    details: [
      "Extensive 7-night desert journey",
      "Camel rides across multiple desert terrains",
      "Camp under the stars each night",
      "All meals and warm bedding included",
      "Most comprehensive desert experience",
    ],
    image: adventureImg,
  },
  {
    id: "multi-day",
    title: "Multi-Day Camel Safari",
    description: "Fully customizable safari from 3 days to 22 days. Jeep support and drinking water included. Flexible schedule.",
    price: 2150,
    priceLabel: "/person/night",
    nights: 2,
    minPeople: 2,
    duration: "Min 3 Days / 2 Nights",
    details: [
      "Fully customizable safari — you choose the duration",
      "Minimum 3 days / 2 nights, up to 22 days / 21 nights",
      "Jeep support vehicle and drinking water included",
      "Start and end time is flexible",
      "All meals freshly cooked in the desert",
      "Minimum 2 people required",
    ],
    image: jeepSafariImg,
  },
];

const DesertSafari = () => (
  <ServicePageLayout
    icon={<TreePine className="h-5 w-5 text-gold" />}
    navTitle="Desert Safari"
    heroImage={camelSafariImg}
    heroSubtitle="Explore the Thar Desert"
    heroTitle="Desert Safari Adventures"
    heroDescription="Choose from our curated desert experiences — from half-day camel rides to multi-day expeditions across the Thar."
    activities={activities}
    bookingType="Desert Safari"
  />
);

export default DesertSafari;
